/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/Album.vue')['default']
    Albums: typeof import('./src/components/Albums.vue')['default']
    Artists: typeof import('./src/components/Artists.vue')['default']
    ArtistThumb: typeof import('./src/components/ArtistThumb.vue')['default']
    ChangeAlbumArt: typeof import('./src/components/ChangeAlbumArt.vue')['default']
    FooterPlayer: typeof import('./src/components/FooterPlayer.vue')['default']
    GenreBottle: typeof import('./src/components/GenreBottle.vue')['default']
    HeaderAndSearch: typeof import('./src/components/HeaderAndSearch.vue')['default']
    HeroAlbum: typeof import('./src/components/HeroAlbum.vue')['default']
    HRule: typeof import('./src/components/HRule.vue')['default']
    IconFluentDarkTheme24Regular: typeof import('~icons/fluent/dark-theme24-regular')['default']
    IconNrkChevronLeft: typeof import('~icons/nrk/chevron-left')['default']
    IconNrkChevronRight: typeof import('~icons/nrk/chevron-right')['default']
    IconNrkClock: typeof import('~icons/nrk/clock')['default']
    IconNrkClose: typeof import('~icons/nrk/close')['default']
    IconNrkDice3: typeof import('~icons/nrk/dice3')['default']
    IconNrkDice3Active: typeof import('~icons/nrk/dice3-active')['default']
    IconNrkDownload: typeof import('~icons/nrk/download')['default']
    IconNrkList: typeof import('~icons/nrk/list')['default']
    IconNrkMediaFfw: typeof import('~icons/nrk/media-ffw')['default']
    IconNrkMediaJumpto: typeof import('~icons/nrk/media-jumpto')['default']
    IconNrkMediaNext: typeof import('~icons/nrk/media-next')['default']
    IconNrkMediaPause: typeof import('~icons/nrk/media-pause')['default']
    IconNrkMediaPlay: typeof import('~icons/nrk/media-play')['default']
    IconNrkMediaPlaylist: typeof import('~icons/nrk/media-playlist')['default']
    IconNrkMediaPrevious: typeof import('~icons/nrk/media-previous')['default']
    IconNrkMediaStop: typeof import('~icons/nrk/media-stop')['default']
    IconNrkMediaVolume1: typeof import('~icons/nrk/media-volume1')['default']
    IconNrkMediaVolume2: typeof import('~icons/nrk/media-volume2')['default']
    IconNrkMediaVolume3: typeof import('~icons/nrk/media-volume3')['default']
    IconNrkMening: typeof import('~icons/nrk/mening')['default']
    IconNrkProgress: typeof import('~icons/nrk/progress')['default']
    IconNrkRefresh: typeof import('~icons/nrk/refresh')['default']
    IconNrkReorder: typeof import('~icons/nrk/reorder')['default']
    IconNrkSearch: typeof import('~icons/nrk/search')['default']
    IconNrkSettings: typeof import('~icons/nrk/settings')['default']
    IconNrkUserLoggedin: typeof import('~icons/nrk/user-loggedin')['default']
    ImageSelector: typeof import('./src/components/ImageSelector.vue')['default']
    ImageSelectorImage: typeof import('./src/components/ImageSelectorImage.vue')['default']
    LyricsDisplay: typeof import('./src/components/LyricsDisplay.vue')['default']
    NavArt: typeof import('./src/components/NavArt.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    PlayButton: typeof import('./src/components/PlayButton.vue')['default']
    PlayerProgressBar: typeof import('./src/components/PlayerProgressBar.vue')['default']
    RefreshHeader: typeof import('./src/components/RefreshHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResults: typeof import('./src/components/SearchResults.vue')['default']
    SettingsDropDown: typeof import('./src/components/SettingsDropDown.vue')['default']
    TopGenres: typeof import('./src/components/TopGenres.vue')['default']
    Tracks: typeof import('./src/components/Tracks.vue')['default']
    UserManagement: typeof import('./src/components/UserManagement.vue')['default']
    ZButton: typeof import('./src/components/ZButton.vue')['default']
  }
}
