/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/Album.vue')['default']
    ArtistThumb: typeof import('./src/components/ArtistThumb.vue')['default']
    GenreBottle: typeof import('./src/components/GenreBottle.vue')['default']
    HeaderAndSearch: typeof import('./src/components/HeaderAndSearch.vue')['default']
    HeroAlbum: typeof import('./src/components/HeroAlbum.vue')['default']
    Home: typeof import('./src/components/routes/Home.vue')['default']
    IconTablerArrowsShuffle: typeof import('~icons/tabler/arrows-shuffle')['default']
    IconTablerChevronLeft: typeof import('~icons/tabler/chevron-left')['default']
    IconTablerChevronRight: typeof import('~icons/tabler/chevron-right')['default']
    IconTablerDice6: typeof import('~icons/tabler/dice6')['default']
    IconTablerMoonStars: typeof import('~icons/tabler/moon-stars')['default']
    IconTablerPlayerPause: typeof import('~icons/tabler/player-pause')['default']
    IconTablerPlayerPlay: typeof import('~icons/tabler/player-play')['default']
    IconTablerPlayerPlayFilled: typeof import('~icons/tabler/player-play-filled')['default']
    IconTablerPlayerSkipBack: typeof import('~icons/tabler/player-skip-back')['default']
    IconTablerPlayerSkipBackFilled: typeof import('~icons/tabler/player-skip-back-filled')['default']
    IconTablerPlayerSkipForward: typeof import('~icons/tabler/player-skip-forward')['default']
    IconTablerPlayerSkipForwardFilled: typeof import('~icons/tabler/player-skip-forward-filled')['default']
    IconTablerRepeat: typeof import('~icons/tabler/repeat')['default']
    IconTablerSearch: typeof import('~icons/tabler/search')['default']
    IconTablerSun: typeof import('~icons/tabler/sun')['default']
    IconTablerUser: typeof import('~icons/tabler/user')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RecentlyAddedAlbums: typeof import('./src/components/RecentlyAddedAlbums.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopGenres: typeof import('./src/components/TopGenres.vue')['default']
  }
}
