/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    IconTablerArrowsShuffle: typeof import('~icons/tabler/arrows-shuffle')['default']
    IconTablerEdit: typeof import('~icons/tabler/edit')['default']
    IconTablerHome: typeof import('~icons/tabler/home')['default']
    IconTablerLibraryPlus: typeof import('~icons/tabler/library-plus')['default']
    IconTablerMoonStars: typeof import('~icons/tabler/moon-stars')['default']
    IconTablerPlayerPlayFilled: typeof import('~icons/tabler/player-play-filled')['default']
    IconTablerPlayerSkipBackFilled: typeof import('~icons/tabler/player-skip-back-filled')['default']
    IconTablerPlayerSkipForwardFilled: typeof import('~icons/tabler/player-skip-forward-filled')['default']
    IconTablerSun: typeof import('~icons/tabler/sun')['default']
    IconTablerTags: typeof import('~icons/tabler/tags')['default']
    IconTablerUpload: typeof import('~icons/tabler/upload')['default']
    IconTablerUser: typeof import('~icons/tabler/user')['default']
    IconTablerVinyl: typeof import('~icons/tabler/vinyl')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
