import { defineConfig, presetAttributify, presetWind4, transformerDirectives, transformerVariantGroup } from 'unocss'

export default defineConfig({
  shortcuts: {
    'corner-cut': 'rounded-none [@supports(corner-top-left-shape:bevel)]:rounded-tl-12px [@supports(corner-top-left-shape:bevel)]:[corner-top-left-shape:_bevel]',
    'corner-cut-large': 'rounded-none [@supports(corner-top-left-shape:bevel)]:rounded-tl-36px [@supports(corner-top-left-shape:bevel)]:[corner-top-left-shape:_bevel]',
    'media-control-button': 'flex cursor-pointer items-center justify-center border-none bg-white/0 font-semibold outline-none lg:size-12 size-10',
    'text-primary': 'dark:text-text-100 text-text-900',
    'text-muted': 'dark:text-text-200 text-text-800',
    'link': 'hover:(underline underline-white) cursor-pointer',
    'border-primary': 'dark:border-background-600 border-background-300 border-solid border-1',
    'border-muted': 'dark:border-background-700 border-background-200 border-solid border-1',
    'background-1': 'dark:bg-background-900 bg-background-100',
    'background-2': 'dark:bg-background-800 bg-background-200',
    'background-3': 'dark:bg-background-700 bg-background-300',
    'background-grad-2': 'dark:from-background-800 from-background-200 bg-gradient-to-r',
    'z-button': 'border-1 border-solid border-primary relative font-semibold corner-cut flex cursor-pointer items-center justify-center cursor-pointer px-3 py-1 text-sm outline-none transition-all duration-200 text-muted background-2 hover:(from-main-200 text-primary bg-gradient-to-br border-main-400)',
    'footer-icon': 'scale-100 text-lg text-muted transition-all duration-100 hover:scale-130 group-hover/button:scale-130 lg:text-xl active:text-main-500',
    'footer-icon-disabled': 'scale-100 text-lg text-muted lg:text-xl opacity-50',
    'footer-icon-on': 'scale-110 text-lg text-main-400 transition-all duration-100 hover:scale-130 group-hover/button:scale-130 lg:text-xl',
    'track-grid': 'items-center gap-4 grid grid-cols-[40px_minmax(0,_1fr)_40px_20px] md:grid-cols-[40px_minmax(0,_1.2fr)_40px_minmax(0,_0.9fr)_60px_20px] lg:grid-cols-[40px_minmax(0,_1.2fr)_40px_minmax(0,_0.9fr)_minmax(0,_0.9fr)_60px_20px] xl:grid-cols-[40px_minmax(0,_1.2fr)_40px_minmax(0,_0.9fr)_minmax(0,_0.9fr)_60px_40px_40px_20px]',
    'input-text': 'background-2 mt-2 p-2 border-1 border-gray-300 border-solid w-28rem focus:outline-none focus:ring-1 focus:ring-main-200 dark:focus:ring-main-400',
  },
  theme: {
    colors: {
      text: {
        50: 'hsl(from var(--main-colour) calc(h + 180) 6 95%)',
        100: 'hsl(from var(--main-colour) calc(h + 180) 6 90%)',
        200: 'hsl(from var(--main-colour) calc(h + 180) 6 80%)',
        300: 'hsl(from var(--main-colour) calc(h + 180) 6 70%)',
        400: 'hsl(from var(--main-colour) calc(h + 180) 6 60%)',
        500: 'hsl(from var(--main-colour) calc(h + 180) 6 50%)',
        600: 'hsl(from var(--main-colour) calc(h + 180) 6 40%)',
        700: 'hsl(from var(--main-colour) calc(h + 180) 6 30%)',
        800: 'hsl(from var(--main-colour) calc(h + 180) 6 20%)',
        900: 'hsl(from var(--main-colour) calc(h + 180) 6 10%)',
        950: 'hsl(from var(--main-colour) calc(h + 180) 6 5%)',
      },
      background: {
        50: 'hsl(from var(--main-colour) calc(h + 180) 6 95%)',
        100: 'hsl(from var(--main-colour) calc(h + 180) 6 90%)',
        200: 'hsl(from var(--main-colour) calc(h + 180) 6 80%)',
        300: 'hsl(from var(--main-colour) calc(h + 180) 6 70%)',
        400: 'hsl(from var(--main-colour) calc(h + 180) 6 60%)',
        500: 'hsl(from var(--main-colour) calc(h + 180) 6 50%)',
        600: 'hsl(from var(--main-colour) calc(h + 180) 6 40%)',
        700: 'hsl(from var(--main-colour) calc(h + 180) 6 30%)',
        800: 'hsl(from var(--main-colour) calc(h + 180) 6 20%)',
        900: 'hsl(from var(--main-colour) calc(h + 180) 6 10%)',
        950: 'hsl(from var(--main-colour) calc(h + 180) 6 5%)',
      },
      main: {
        50: 'hsl(from var(--main-colour) h 70% 95%)',
        100: 'hsl(from var(--main-colour) h 70% 90%)',
        200: 'hsl(from var(--main-colour) h 70% 80%)',
        300: 'hsl(from var(--main-colour) h 70% 70%)',
        400: 'hsl(from var(--main-colour) h 70% 60%)',
        500: 'hsl(from var(--main-colour) h 70% 50%)',
        600: 'hsl(from var(--main-colour) h 70% 40%)',
        700: 'hsl(from var(--main-colour) h 70% 30%)',
        800: 'hsl(from var(--main-colour) h 70% 20%)',
        900: 'hsl(from var(--main-colour) h 70% 10%)',
        950: 'hsl(from var(--main-colour) h 70% 5%)',
      },
      hero: {
        400: 'hsl(from var(--hero-colour) h 70% 60%)',
      },
    },
  },
  presets: [
    presetWind4({
      preflights: {
        reset: true,
      },
    }),
    presetAttributify(),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})
